DROP TABLE IF EXISTS tabela uczniowie;
CREATE TABLE tabela uczniowie (
    id INTEGER PRIMARY KEY,
    Nazwisko TEXT(30),
    Imie1 TEXT(15),
    Imie2 TEXT(15)  
);

DROP TABLE IF EXISTS tabela klasy;
CREATE TABLE tabela klasy (
    Nr_ucz INTEGER,
    Dzien INTEGER,
    Miesiac INTEGER,
    Rok INTEGER,
    M_urodzenia TEXT(20),
    Wojewodztwo TEXT(30),
    FOREIGN KEY (Nr_ucz) REFERENCES nazwiska(Nr_ucz)
);

DROP TABLE IF EXISTS tabela przedmioty;
CREATE TABLE tabela przedmioty (
    Nr_ucz INTEGER,
    Zach TEXT,
    Rel_Ety DECIMAL DEFAULT NULL,
    Jpol DECIMAL DEFAULT NULL,
    Jang DECIMAL DEFAULT NULL,
    Jniem DECIMAL DEFAULT NULL,
    Mat DECIMAL DEFAULT NULL,
    Hist DECIMAL DEFAULT NULL,
    Geog DECIMAL DEFAULT NULL,
    Biol DECIMAL DEFAULT NULL,
    Fiz DECIMAL DEFAULT NULL,
    Che DECIMAL DEFAULT NULL,
    Tech DECIMAL DEFAULT NULL,
    Info DECIMAL DEFAULT NULL,
    Plas DECIMAL DEFAULT NULL,
    PO DECIMAL DEFAULT NULL,
    WF DECIMAL DEFAULT NULL
    FOREIGN KEY (Nr_ucz) REFERENCES nazwiska(Nr_ucz)
);

DROP TABLE IF EXISTS tabela oceny;
CREATE TABLE tabela oceny (
    Nr_ucz INTEGER,
    Zach TEXT,
    Rel_Ety DECIMAL DEFAULT NULL,
    Jpol DECIMAL DEFAULT NULL,
    Jang DECIMAL DEFAULT NULL,
    Jniem DECIMAL DEFAULT NULL,
    Mat DECIMAL DEFAULT NULL,
    Hist DECIMAL DEFAULT NULL,
    Geog DECIMAL DEFAULT NULL,
    Biol DECIMAL DEFAULT NULL,
    Fiz DECIMAL DEFAULT NULL,
    Che DECIMAL DEFAULT NULL,
    Tech DECIMAL DEFAULT NULL,
    Info DECIMAL DEFAULT NULL,
    Plas DECIMAL DEFAULT NULL,
    PO DECIMAL DEFAULT NULL,
    WF DECIMAL DEFAULT NULL
    FOREIGN KEY (Nr_ucz) REFERENCES nazwiska(Nr_ucz)
);
